@startuml
class Health {
    + ResetHealth() : void
    + ResetHealthWithNewMaxHealth(health:int) : void
    + TakeDamage(damage:int, hitDirection:Vector2, knockbackMultiplier:float) : void
    + GetMaxHealth() : int
    + GetCurrentHealth() : int
    + SetCurrentHealth(health:int) : void
    + IsHackable() : bool
    + ApplyKnockback(hitDirection:Vector2, multiplier:float) : void
    + TriggerIFrame() : void
    + Heal(health:int) : void
    + HealPercent(percent:double) : void
    + GetMortality() : bool
    + SetMortality(mortal:bool) : void
    + SetHackableHealth(health:int) : void
}
MonoBehaviour <|-- Health
Health --> "OnHackable" UnityEvent
Health --> "OriginalColor" Color
@enduml
