@startuml
class SpawnerController {
    + SetSpawnerSettings(settings:SpawnerSettings) : void
    + ReachedSpawnedObjectsLimit() : bool
}
enum SpawningGameObject {
    SWORD_CHARGER,
    BOMBER,
    SWORD_WIELDER,
    BOSS_PUPPETEER_TURRET,
}
class SpawnerSettings {
    + spawnCountMax : int?
    + spawnCountMin : int?
    + spawnIntervalMax : float?
    + spawnIntervalMin : float?
    + waveCount : int?
    + waveInterval : float?
    + currentWave : int?
    + delayedStart : float?
    + maxSpawnObjects : int?
    + spawningGameObject : SpawningGameObject?
}
MonoBehaviour <|-- SpawnerController
SpawnerController +-- SpawningGameObject
SpawnerController +-- SpawnerSettings
@enduml
