@startuml
class PauseMenu {
    + {static} GameIsPaused : bool = false
    + Resume() : void
    + Restart() : void
    + Setting() : void
    + Quit() : void
}
MonoBehaviour <|-- PauseMenu
PauseMenu --> "pauseMenuUI" GameObject
@enduml
