@startuml
class EquipmentSlot {
    + Select() : void
    + Deselect() : void
}
MonoBehaviour <|-- EquipmentSlot
EquipmentSlot --> "selectedColor" Color
EquipmentSlot --> "notSelectedColor" Color
@enduml
